New log file opened at Tue Nov 24 00:41:05 COT 2015 by 8128@USER-HP
Taking next connection to: 56430
New client attempting to connect on port: 56431-56430
  Address = /192.168.0.8:56430
This client on port 56431 has uuid 69137ebc-234f-48b8-bb8d-b70a432fa703 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-69137ebc-234f-48b8-bb8d-b70a432fa703
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56430
New client attempting to connect on port: 61170-56430
  Address = /192.168.0.8:56430
Handshake exception on socket: 61170
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 56430
New client attempting to connect on port: 61171-56430
  Address = /192.168.0.8:56430
This client on port 61171 has uuid 66a431e0-a355-417e-a2e1-dbf87367bd70 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: play-fork-run-66a431e0-a355-417e-a2e1-dbf87367bd70
Taking next connection to: 56430
